# Nom du workflow
name: Generate Snake Animation

# Événements déclencheurs
on:
  push:
    branches:
      - main       # Déclenchement uniquement sur la branche `main`
  schedule:        # Planification automatique (exemple : chaque jour à minuit)
    - cron: "0 0 * * *"

# Définition des jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Générer l'animation Snake
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Nom d'utilisateur GitHub (dynamique ou fixe)
          github_user_name: ${{ github.repository_owner }}
          
          # Fichiers de sortie et options de personnalisation
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Étape 3 : Ajouter les fichiers générés à un dépôt ou une branche
      - name: Push generated snake
        uses: github-actions-x/commit@v2
        with:
          files: dist/**    # Spécifie les fichiers à ajouter
          branch: main      # Branche cible pour les fichiers générés
          commit-message: "Update snake animation"
